name: Run Script and Push Changes
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - doc

jobs:
  run-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitPython

      - name: Run update blog
        run: |
          chmod +x ./autodo.sh  # 确保脚本可执行
          ./autodo.sh

      - name: Commit changes
        run: | 
          git config --local user.email "formatjn2019@gmail.com"
          git config --local user.name "zx"
          git add .
          git commit -m "Run autodo.sh and update changes" || echo "No changes to commit"
          git push origin HEAD:main --force